name: build-lorier

on:
  push:
    branches:
      - main

jobs:
  build-lorier:
    runs-on: ubuntu-latest
    steps:
      - name: Set ruby version
        uses: ruby/ruby-setup@v1
        with:
          ruby-version: 2.6.6
