name: build-lorier

on:
  push:
    branches:
      - main

jobs:
  test-lorier:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set ruby version
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
      - name: Cache ruby gem
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ruby-gem-cache
      - name: Bundle install
        run: bundle install
      - name: Setup postgres
        run: sudo apt install libpq-dev
      - name: Run test
        env:
          DB_DATABASE: postgres
          DB_HOST: localhost
          DB_USER: postgres
          DB_PASSWORD: postgres
          RAILS_ENV: test
        run: |
          bin/rails db:setup
          COVERAGE=true bundle exec rspec spec -f d
