name: build-lorier

on:
  push:
    branches:
      - main

jobs:
  test-lorier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set ruby version
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
      - name: Bundle install
          run: bundle install
      - name: Setup postgres
          run: sudo apt install libpq-dev
      - name: Run test
          env:
            PG_DATABASE: postgres
            PG_HOST: localhost
            PG_USER: postgres
            PG_PASSWORD: password
            RAILS_ENV: test
          run: |
            bin/rails db:setup
            COVERAGE=true bundle exec rspec spec -f d
